# Cloudflare Pages configuration
name = "homeharvest-webapp"
compatibility_date = "2024-08-28"

[build]
command = "echo 'No build required for static site'"
cwd = "."

[env.production]
# Production environment variables
ENVIRONMENT = "production"

[env.preview]  
# Preview environment variables
ENVIRONMENT = "preview"