# Cloudflare Pages configuration
name = "homeharvest-webapp"
compatibility_date = "2024-08-28"

# No build configuration needed for static site
# Files in public/ directory will be deployed automatically